services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      OLLAMA_API_URL: http://ollama:11434  # Internal URL for Ollama API
    env_file:
      - .env  # Loading environment variables from .env file
    depends_on:
      - db
      - ollama
    command: streamlit run app.py

  db:
    image: mysql:8.0.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    hostname: ${MYSQL_HOST}
    ports:
      - "3306:3306"
    env_file:
      - .env 
    volumes:
      - mysql_data:/var/lib/mysql

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./download-model.sh:/download-model.sh
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/download-model.sh"]

volumes:
  mysql_data:
  ollama: