version: '3'
services:
  app:
    build: .
    ports:
      - "8501:8501"  # Expose port 8501 for Streamlit
    environment:
      - DB_HOST=db
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: